# CIFAR-10 CNN Configuration File

# Model Architecture Settings
model:
  num_classes: 10
  dropout_rate: 0.3

# Training Hyperparameters
training:
  num_epochs: 30
  learning_rate: 0.001
  weight_decay: 0.0001
  step_size: 15          # Learning rate scheduler step size
  gamma: 0.1             # Learning rate decay factor
  early_stopping: false
  patience: 10

# Data Configuration
data:
  batch_size: 128
  num_workers: 2
  pin_memory: true
  data_root: "./data"
  download: true
  
  # Data Augmentation Parameters
  transforms:
    flip_prob: 0.5
    rotation_degrees: 10
    crop_padding: 4
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1

# File Paths
paths:
  checkpoint_dir: "./checkpoints"
  results_dir: "./results"
  logs_dir: "./logs"

# Experiment Settings
experiment:
  name: "cifar10_cnn_baseline"
  seed: 42
  save_metrics: true
  save_plots: true